services:
  api:
    build:
      context: ./api
    environment:
      - RUST_LOG=api=debug
      - ADDRESS=0.0.0.0:80
      - ORIGIN=${FRONTEND_URL}

  realtime:
    build:
      context: ./realtime
    environment:
      - RUST_LOG=realtime=debug
      - ADDRESS=0.0.0.0:80
      - ORIGIN=${FRONTEND_URL}

  web:
    build:
      context: ./dashboard
    depends_on:
      - realtime
      - api
    environment:
      - NEXT_PUBLIC_LIVE_URL=${REALTIME_URL}
      - API_URL=${API_URL}
